### ISSUE TITLE
Surveys displayed in plot_ages()

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfplot#32]
I am curious about why the attached age bubble plot for P cod is showing panels for surveys that have been filtered out of the data passed to the plot_ages() function:

x <- get_survey_samples(222) 
x <- filter(x,is.element(x$survey_abbrev,c("SYN HS", "SYN QCS","SYN WCVI")))
unique(x$survey_abbrev)
[1] "SYN HS"   "SYN QCS"  "SYN WCVI"

png(paste0(outDir,"Raw_Age_Data.png"),width = 960, height = 960)
  g <- tidy_ages_raw(x, ageing_method_codes = 6) %>%
    plot_ages()
  g
dev.off()
![raw_age_data](https://user-images.githubusercontent.com/2694518/40454946-9b093d2c-5e9f-11e8-9f0e-93c6b71d668f.png)

**Comment by robynforrest** [comment]
p.s. Hope you're proud of me for not sending this as an email ;-)

**Comment by robynforrest** [comment]
Same thing with plot_lengths()

**Comment by seananderson** [comment]
The way it's set up right now, the intention is to specify which surveys you want included to the argument `surveys` in `tidy_ages_raw()` or related functions. The panels will also be laid out in the order that you specify the surveys to the tidy function. Internally, it sets the factor levels appropriately. 

I finally finished filling in all the documentation recently and also started an auto-generated website with the documentation. E.g.
https://pbs-assess.github.io/gfplot/reference/tidy_comps.html

```r
get_survey_samples(222) %>%
  tidy_ages_raw(
    survey = c("SYN HS", "SYN QCS", "SYN WCVI"), 
    ageing_method_codes = 6) %>%
  plot_ages()
ggplot2::ggsave(paste0(outDir, "Raw_Age_Data.png"), width = 5, height = 5)
```

I set up the functions that way because of the synopsis report where we always need to have the same panels regardless of whether there are data. An alternative would be to set `survey = NULL` as the default and have it plot all included surveys unless a character vector is supplied. 

Note that because it's a ggplot plot you can use the `ggsave()` function, which by default saves the last plot. As an added bonus, `ggsave()` will never leave the plotting device open and lets you specify the dimensions in inches.

**Comment by robynforrest** [comment]
OK got it thanks
