### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mkapur** [pbs-assess/gfplot#60]
I'm trying to work with the gfsynopsis package and need to install this as a dependency, but when I run
`devtools::install_github("pbs-assess/gfplot")`

I obtain 
`Downloading GitHub repo pbs-assess/gfplot@master
Error in read.dcf(path) : 
  Found continuation line starting '   person("Rowan", " ...' at begin of record.`

Which I am not sure how to get past. Thanks!

**Comment by seananderson** [comment]
My guess is that's a problem with one of the PBS R packages maintained by Rowan since I don't have the code `person("Rowan"` anywhere in my packages, but Rowan would in his. https://github.com/pbs-software I can't replicate that error myself. The obvious candidate would be

```r
devtools::install_github("pbs-software/pbs-data/PBSdata/")
```

The only other possibility would be PBSmapping, but that's coming from CRAN, so it's less likely.

Bigger picture though, unless you are on our DFO network there may not be much use to installing these packages since they depend on access to our SQL databases. There are bits and pieces of them that could be used elsewhere such as the model fitting and plotting functions if you were to get data formatted in exactly the same way.

If you're still stuck and want to get this installed, then try running a `traceback()` after the error and let me know what it says.

**Comment by mkapur** [comment]
No worries -- I am working on building an operating model for sablefish including Canadian fisheries and was curious about the materials here as reference (assuming sablefish was included) -- this isn't a pressing need. Thanks for your quick reply!

**Comment by seananderson** [comment]
I can send you the pages for sablefish from the report and connect you with some of the people here working on them if you want.

**Comment by mkapur** [comment]
I would really appreciate that! I'm at kapurm [at] uw.edu. I'm currently working with Brendan Connors at DFO as well as Sean Cox, and Luke Rodgers (a new postdoc they hired). It's been quite a lift to get everyone in the same room but things have been going well so far. Thanks for your help!

**Comment by MirenAltuna** [comment]
I had the same problem with RStudio 3.5 and I solved it using RStudio 3.4 version... Just in case someone need it this information ;)

**Comment by MirenAltuna** [comment]
I had the same problem with RStudio 3.5 and I solved it using RStudio 3.4 version... Just in case someone need this information ;)
