### ISSUE TITLE
Building gfplot under R version 4.0.0.

### ISSUE THREAD

**Issue by NormOlsen** [pbs-assess/gfplot#63]
When executing:
`devtools::install_github("pbs-assess/gfplot")`

under R 4.0.0. I receive the following error:

> Error: Failed to install 'gfplot' from GitHub:
  Failed to install 'sdmTMB' from GitHub:
  (converted from warning) unable to access index for repository https://inla.r-inla-download.org/R/stable/bin/windows/contrib/4.0:
  cannot open URL 'https://inla.r-inla-download.org/R/stable/bin/windows/contrib/4.0/PACKAGES'

**Comment by seananderson** [comment]
R-INLA is apparently not compatible with R 4.0 yet. http://www.r-inla.org/?place=msg%2Fr-inla-discussion-group%2FibHgZjvmJLE%2FsUsfLYcJBwAJ If you need gfplot before then, assuming you don't need any of the spatial modelling stuff, we can comment it and sdmTMB out of the DESCRIPTION file in a branch.

Also, just in case it wasn't obvious, all data-getting functions are now in https://github.com/pbs-assess/gfdata and will be removed from gfplot soon.

**Comment by NormOlsen** [comment]
I don't think I require gfplot unless it's used by csasdown; it was in a list of suggested pbs-assess packages that I was installing on a new computer. So mainly I was just flagging this as an issue.

**Comment by quang-huynh** [comment]
Would it be feasible to set sdmTMB (and thus INLA) as a Suggests package instead?

**Comment by seananderson** [comment]
Probably not without breaking R CMD check here, but I could if needed. After much fiddling with R 4.0, I gave up at the time and suggested that INLA be installed first for sdmTMB:

```r
install.packages("INLA", repos = c(getOption("repos"), 
  INLA = "https://inla.r-inla-download.org/R/stable"), dep = TRUE)
```

because I couldn't figure out of DESCRIPTION file that worked.

That seems to be working on R 4.0. Travis does the same https://github.com/pbs-assess/sdmTMB/blob/bcde813cad8f5ac2e7894e19f5fde861e1dbb93e/.travis.yml#L17

https://github.com/pbs-assess/sdmTMB#installation

Does that solve your problems or is there some other issue?

**Comment by quang-huynh** [comment]
It's a nice-to-have rather a necessity as there's signficant install time with INLA and sdmTMB.
